baseURL = "https://yanziv.github.io/"
relativeURLs = false
uglyURLs = false
canonifyURLs = true
title = "Yanzi Lin (Veronica)"
theme = "academimal-theme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Student in Societal Computing, Carnegie Mellon University School of Computer Science"
    logo = "picture.jpg" 

[services]
  [services.googleAnalytics]
    ID = ''

